---
title: "Assignmnet 4"
author: "Yani Pohl and Marie Bouffard"
date: "11/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

### Introduction

DO

### Data and Methods

### Results

```{r, echo=FALSE}

# Attach packages 

library(tidyverse)
library(dplyr)
library(janitor)
library("RColorBrewer")

#read in data, clean names to lowercase snakecase, and uncount the count column

lobster_abundance <- read_csv("lobster_abundance_sbc_lter.csv", na = "-99999") %>% 
  clean_names() %>% 
  uncount(count)

      
```

```{r}

# Results A


# Create dataframe for lobster abundance (count) by sample site for each year. Add column to df that indicates MPA status

lobster_yr <- lobster_abundance %>% 
  select(year, site, size_mm) %>% 
  group_by(year, site) %>% 
  count(year, site) %>% 
  rename(count = n) %>% 
  mutate(mpa_status = case_when(
    site %in% c('NAPL', "IVEE") ~ "Marine Protected Area",
    site %in% c("AQUE", "CARP", "MOHK") ~ "Unprotected Area"))

# Create line graph to visulize changes in lobster abundance by site from 2012 - 2018

ggplot(lobster_yr, aes(x = year, y = count, color = site)) +
  geom_line(aes(linetype = mpa_status, 
                color = site)) +
  labs(title = "Santa Barbara Lobster Abundance from 2012 - 2018",
       x = "Year",
       y = "Lobster Abundance (individuals)",
       caption = "Fig. 1 - Lobster populations at five reef site along the Santa Barbara coast between 2012 and 2018.\n  The two study reefs with marine protection stutus show the  largest increase in abundance\n  during this time period while the  three unprotected areas show slower increases.",
       linetype = "Site Status") +
  scale_color_discrete(name = "Survey Site", 
                     labels = c("Arroyo Quemado", 
                                "Carpinteria", 
                                "Isla Vista", 
                                "Mohawk", 
                                "Naples")) +
  theme(panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        plot.title = element_text(hjust = .5),
        plot.caption = element_text(hjust = .5),
        legend.key = element_blank())
```

Graph 1 explination put here. 





```{r}

# Results B

# Create dataframe of lobster sizes for each site for 2012 and 2018

lobster_size <- lobster_abundance %>% 
  select(year, site, size_mm) %>% 
  filter(year %in% c(2012, 2018)) %>% 
  mutate(year = as.character(year))

lobster_size$site[lobster_size$site == "AQUE"] <- "Arroyo Quemado"

lobster_size$site[lobster_size$site == "IVEE"] <-  "Isla Vista"

lobster_size$site[lobster_size$site == "NAPL"] <- "Naples"

lobster_size$site[lobster_size$site == "CARP"] <- "Carpenteria"

lobster_size$site[lobster_size$site == "MOHK"] <- "Mohawk"

# Create density plot of lobserter sizes for 2012 and 2018 at each sample site

ggplot(lobster_size) + 
  geom_density(aes(fill = year, x = size_mm, color = year),
               alpha = .5) +
  facet_wrap(~site, scales='free') +
  scale_x_continuous(limits=c(20,150)) +
  scale_fill_manual(values = c("#B2182B", "#2166AC")) +
  scale_color_manual(values = c("#B2182B", "#2166AC")) +
  labs(title = "Distribution of Lobster Size in Santa Barbara, 2012, 2018",
       x = "Lobserter Size (mm)",
       y = "Density") +
  theme(panel.margin = unit(2, "lines"),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(colour = "grey"),
        legend.position = "top",
        legend.title = element_blank())

    
```

Graph 2 explination put here


```{r}

# Results C

# Create a new dataframe that adds MPA status column to lobster size dataframe

mpa_lobster_size <- lobster_size %>%
  mutate(mpa_status = case_when(
    site %in% c("Naples", "Isla Vista") ~ "MPA",
    site %in% c("Arroyo Quemado", "Carpenteria", "Mohawk") ~ "Non MPA"))

# Create summary table of mean lobster size, sd and sample size for MPA and Non MPA sites for 2012 and 2018 

mpa_mean_size <- mpa_lobster_size %>% 
  group_by(mpa_status, year) %>% 
  summarize( mean = mean(size_mm, na.rm = TRUE,) %>% round(2),
             sd = sd(size_mm, na.rm = TRUE) %>% round(2),
             sample = n())

# Determine if there is a significant difference in lobster size between MPA and non-MPA sites in 2012. 

lobster_2012_mpa <- mpa_lobster_size %>% 
  filter(year == 2012, mpa_status == "MPA") %>% 
  pull(size_mm)

lobster_2012_nonmpa <- mpa_lobster_size %>% 
  filter(year == 2012, mpa_status == "Non MPA") %>% 
  pull(size_mm)

`2012_ttest` <- t.test(lobster_2012_mpa, lobster_2012_nonmpa)

`2012_ttest`

# Determine if there is a significant difference in lobster size between MPA and non-MPA sites in 2018.

lobster_2018_mpa <- mpa_lobster_size %>% 
  filter(year == 2018, mpa_status == "MPA") %>% 
  pull(size_mm)

lobster_2018_nonmpa <- mpa_lobster_size %>% 
  filter(year == 2018, mpa_status == "Non MPA") %>% 
  pull(size_mm)

`2018_ttest` <- t.test(lobster_2018_mpa, lobster_2018_nonmpa)

`2018_ttest`

# Determine if there a significant difference in lobsters observed in 2012 vs. 2018 for MPA sites only.

mpa_ttest <- t.test(lobster_2012_mpa, lobster_2018_mpa)

mpa_ttest


# Determine if there is a significant difference in lobsters observed in 2012 vs. 2018 for non-MPA sites.

nonmpa_ttest <- t.test(lobster_2012_nonmpa, lobster_2018_nonmpa)

nonmpa_ttest

```



### Summary
